package com.Jcare.Jcare.models;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "inventory")
public class Inventory {
    @Id
    private String itemId;       // Auto-generated by MongoDB
    private String itemName;
    private String itemCategory; // e.g., Medicine, Equipment, Supplies
    private int quantity;        // Available stock
    private String unit;         // Optional: e.g., "boxes", "pieces", "ml"
    private String supplier;     // Optional: supplier/vendor name
    private String location;     // Optional: storage location (store room, pharmacy, ward)

    // Constructors, getters, setters are auto-handled by Lombok (@Data)
}